### ISSUE TITLE
Feature Request: VC Mentions support

### ISSUE THREAD

**Issue by DracoClaw** [Twizzer/VC-Double-Click-Join#3]
Please can you add support for mentions of a voice channel in chat? When you do `<#ID>` you are able to mention a voice channel and click it to join. 

![image](https://user-images.githubusercontent.com/34274162/119193026-b0893500-ba89-11eb-9b32-e15ea7883f8c.png)

**Comment by D3SOX** [comment]
I added this via https://github.com/D3SOX/double-click-voice-channels/commit/ea3696f778fb49801fefd04db3c25592596b9cb9
I'll submit a PR in a minute
