### ISSUE TITLE
Bug: Effecting Text Channels

### ISSUE THREAD

**Issue by DracoClaw** [Twizzer/VC-Double-Click-Join#5]
There seems to be a bug that i have to double click text channel mentions also to swap to them.

**Comment by D3SOX** [comment]
This is intended. See the latest commit and issue #3
I think a setting for this would be nice. If I have time I might implement it.

**Comment by DracoClaw** [comment]
It's not intended. What's intended is for voice channels <#!ID> do need a double click. But text channels <#ID> should not be effected by this.

**Comment by D3SOX** [comment]
Sorry I didn't read that it affects text channels. I'll see what I can do about this.

**Comment by DracoClaw** [comment]
Amazing! Thanks so much <3
