### ISSUE TITLE
Not Working

### ISSUE THREAD

**Issue by bignuto** [Twizzer/VC-Double-Click-Join#7]
This plugin has not been working at all for a few weeks. Sorry about being vague it's the best I can do

**Comment by D3SOX** [comment]
Ok nvm it's actually just the location in the object. I'm writing a more robust method to get the channel and submit a PR.

**Comment by Twizzer** [comment]
I trust you do what you think will fix it and submit a push I'll push it.

**Comment by D3SOX** [comment]
Ok, creating a PR in a minute

**Comment by Twizzer** [comment]
Update the plugin all appears to be working correctly thanks again @D3SOX
